server:
  port: 8082

spring:
  profiles:
    active: contentmapper,rabbitmq

dubbo:
  application:
    name: backend-content
  registry:
    address: zookeeper://192.168.137.65:2181
    timeout: 50000